version: '3.9'
services:
    db:
        image: postgres:14.4
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./db/docker-entrypoint-initdb.d/creare-tables.sql:/docker-entrypoint-initdb.d/creare-tables.sql
        logging:
            options:
                max-size: 10m
                max-file: 3
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
    app:
        image: python:3.8-slim-buster
        build: ./app
        ports:
            - "5001:5001"
        healthcheck:
            test: ["CMD-SHELL", "curl --fail -s http:/localhost:5001/ || exit 1"]
            interval: 1m30s
            timeout: 30s
            retries: 5
            start_period: 30s
        depends_on:
            - db:
                condition: service_healthy
volumes:
    db:
        driver: "local"